=== ApptivaAG/trial-store-landingpage-gatsby/content/extendedArticles/articles.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "The Root Schema",
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "required": [
      "group",
      "subgroup",
      "urlPath",
      "sort",
      "name",
      "image",
      "priceFull",
      "price25",
      "mainVariation",
      "variationName",
      "variations"
    ],
    "properties": {
      "group": {
        "$id": "#/items/properties/group",
        "type": "string",
        "title": "The Group Schema",
        "default": "",
        "examples": [
          "herren"
        ],
        "pattern": "^(.*)$"
      },
      "subgroup": {
        "$id": "#/items/properties/subgroup",
        "type": "string",
        "title": "The Subgroup Schema",
        "default": "",
        "examples": [
          "mode"
        ],
        "pattern": "^(.*)$"
      },
      "urlPath": {
        "$id": "#/items/properties/urlPath",
        "type": "string",
        "title": "The Urlpath Schema",
        "default": "",
        "examples": [
          "altea-strickjacke"
        ],
        "pattern": "^(.*)$"
      },
      "sort": {
        "$id": "#/items/properties/sort",
        "type": "integer",
        "title": "The Sort Schema",
        "default": 0,
        "examples": [
          1
        ]
      },
      "name": {
        "$id": "#/items/properties/name",
        "type": "string",
        "title": "The Name Schema",
        "default": "",
        "examples": [
          "Strickjacke von ALTEA"
        ],
        "pattern": "^(.*)$"
      },
      "image": {
        "$id": "#/items/properties/image",
        "type": "string",
        "title": "The Image Schema",
        "default": "",
        "examples": [
          "./img/Herren/Mode/01_ALTEA-Strickjacke/1539775374000.jpeg"
        ],
        "pattern": "^(.*)$"
      },
      "priceFull": {
        "$id": "#/items/properties/priceFull",
        "type": "number",
        "title": "The Pricefull Schema",
        "default": 0.0,
        "examples": [
          209.9
        ]
      },
      "price25": {
        "$id": "#/items/properties/price25",
        "type": "number",
        "title": "The Price25 Schema",
        "default": 0.0,
        "examples": [
          52.4
        ]
      },
      "mainVariation": {
        "$id": "#/items/properties/mainVariation",
        "type": "integer",
        "title": "The Mainvariation Schema",
        "default": 0,
        "examples": [
          1257659205
        ]
      },
      "variationName": {
        "$id": "#/items/properties/variationName",
        "type": "string",
        "title": "The Variationname Schema",
        "default": "",
        "examples": [
          "Gr√∂sse"
        ],
        "pattern": "^(.*)$"
      },
      "variations": {
        "$id": "#/items/properties/variations",
        "type": "array",
        "title": "The Variations Schema",
        "items": {
          "$id": "#/items/properties/variations/items",
          "type": "object",
          "title": "The Items Schema",
          "required": [
            "name",
            "article"
          ],
          "properties": {
            "name": {
              "$id": "#/items/properties/variations/items/properties/name",
              "type": "string",
              "title": "The Name Schema",
              "default": "",
              "examples": [
                "S"
              ],
              "pattern": "^(.*)$"
            },
            "article": {
              "$id": "#/items/properties/variations/items/properties/article",
              "type": "integer",
              "title": "The Article Schema",
              "default": 0,
              "examples": [
                1257659204
              ]
            }
          }
        }
      }
    }
  }
}

=== ApptivaAG/trial-store-landingpage-gatsby/content/extendedArticles/articles.json
[
  {
    "group": "frauen",
    "subgroup": "bags",
    "urlPath": "Umhaengetasche-Love-Moschino",
    "sort": 1,
    "name": "Umh√§ngetasche von LOVE MOSCHINO",
    "image": "./img/Frauen/Taschen/Moschino-Tasche-Gelb.jpg",
    "priceFull": 179.9,
    "price25": 44.9,
    "mainVariation": 1268830803,
    "variationName": "Farbe",
    "variations": [
      {
        "name": "Gelb",
        "article": 1268830803,
        "image": "./img/Frauen/Taschen/Moschino-Tasche-Gelb.jpg",
        "color": "rgb(255,247,0)"
      },
      {
        "name": "Cognac",
        "article": 1268830804,
        "image": "./img/Frauen/Taschen/Moschin-Tasche-Cognac.jpg",
        "color": "#ab5c00"
      }
    ]
  },
  {
    "group": "frauen",
    "subgroup": "bags",
    "urlPath": "shopper-mollerus",
    "sort": 8,
    "name": "Shopper von MOLLERUS",
    "image": "./img/Frauen/Taschen/Shopper-Mollerus-rot.jpg",
    "priceFull": 499,
    "price25": 125,
    "mainVariation": 1185230102,
    "variationName": "Farbe",
    "variations": [
      {
        "name": "schwarz",
        "article": 1185230101,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-schwarz.jpg",
        "color": "#000000"
      },
      {
        "name": "dunkelrot",
        "article": 1185230102,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-rot.jpg",
        "color": "#990101"
      },
      {
        "name": "taupe",
        "article": 1185230104,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-taupe.jpg",
        "color": "#a18e7e"
      }
    ]
  },
  {
    "group": "haushalt",
    "subgroup": "bags",
    "urlPath": "shopper-mollerus",
    "sort": 8,
    "name": "Shopper von MOLLERUS",
    "image": "./img/Frauen/Taschen/Shopper-Mollerus-rot.jpg",
    "priceFull": 499,
    "price25": 125,
    "mainVariation": 1185230102,
    "variationName": "Farbe",
    "variations": [
      {
        "name": "schwarz",
        "article": 1185230101,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-schwarz.jpg",
        "color": "#000000"
      },
      {
        "name": "dunkelrot",
        "article": 1185230102,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-rot.jpg",
        "color": "#990101"
      },
      {
        "name": "taupe",
        "article": 1185230104,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-taupe.jpg",
        "color": "#a18e7e"
      }
    ]
  },
  {
    "group": "herren",
    "subgroup": "bags",
    "urlPath": "shopper-mollerus",
    "sort": 8,
    "name": "Shopper von MOLLERUS",
    "image": "./img/Frauen/Taschen/Shopper-Mollerus-rot.jpg",
    "priceFull": 499,
    "price25": 125,
    "mainVariation": 1185230102,
    "variationName": "Farbe",
    "variations": [
      {
        "name": "schwarz",
        "article": 1185230101,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-schwarz.jpg",
        "color": "#000000"
      },
      {
        "name": "dunkelrot",
        "article": 1185230102,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-rot.jpg",
        "color": "#990101"
      },
      {
        "name": "taupe",
        "article": 1185230104,
        "image": "./img/Frauen/Taschen/Shopper-Mollerus-taupe.jpg",
        "color": "#a18e7e"
      }
    ]
  }
]
